require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PullRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # PullRequest. As you add validations to PullRequest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { 'url' => 'https://github.com/thomasjefferson/usa/pull/1776' }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PullRequestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pull_requests as @pull_requests" do
      pull_request = PullRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pull_requests).should eq([pull_request])
    end
  end

  describe "GET show" do
    it "assigns the requested pull_request as @pull_request" do
      pull_request = PullRequest.create! valid_attributes
      get :show, {:id => pull_request.to_param}, valid_session
      assigns(:pull_request).should eq(pull_request)
    end
  end

  describe "GET new" do
    it "assigns a new pull_request as @pull_request" do
      get :new, {}, valid_session
      assigns(:pull_request).should be_a_new(PullRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested pull_request as @pull_request" do
      pull_request = PullRequest.create! valid_attributes
      get :edit, {:id => pull_request.to_param}, valid_session
      assigns(:pull_request).should eq(pull_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PullRequest" do
        expect {
          post :create, {:pull_request => valid_attributes}, valid_session
        }.to change(PullRequest, :count).by(1)
      end

      it "assigns a newly created pull_request as @pull_request" do
        post :create, {:pull_request => valid_attributes}, valid_session
        assigns(:pull_request).should be_a(PullRequest)
        assigns(:pull_request).should be_persisted
      end

      it "redirects to the pull_request list" do
        post :create, {:pull_request => valid_attributes}, valid_session
        response.should redirect_to(pull_requests_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pull_request as @pull_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        PullRequest.any_instance.stub(:save).and_return(false)
        post :create, {:pull_request => {  }}, valid_session
        assigns(:pull_request).should be_a_new(PullRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PullRequest.any_instance.stub(:save).and_return(false)
        post :create, {:pull_request => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pull_request" do
        pull_request = PullRequest.create! valid_attributes
        # Assuming there are no other pull_requests in the database, this
        # specifies that the PullRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PullRequest.any_instance.should_receive(:update).with(valid_attributes)
        put :update, {:id => pull_request.to_param,
                      :pull_request => valid_attributes }, valid_session
      end

      it "assigns the requested pull_request as @pull_request" do
        pull_request = PullRequest.create! valid_attributes
        put :update, {:id => pull_request.to_param, :pull_request => valid_attributes}, valid_session
        assigns(:pull_request).should eq(pull_request)
      end

      it "redirects to the pull_request" do
        pull_request = PullRequest.create! valid_attributes
        put :update, {:id => pull_request.to_param, :pull_request => valid_attributes}, valid_session
        response.should redirect_to(pull_requests_path)
      end
    end

    describe "with invalid params" do
      it "assigns the pull_request as @pull_request" do
        pull_request = PullRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PullRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => pull_request.to_param, :pull_request => {  }}, valid_session
        assigns(:pull_request).should eq(pull_request)
      end

      it "re-renders the 'edit' template" do
        pull_request = PullRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PullRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => pull_request.to_param, :pull_request => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pull_request" do
      pull_request = PullRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => pull_request.to_param}, valid_session
      }.to change(PullRequest, :count).by(-1)
    end

    it "redirects to the pull_requests list" do
      pull_request = PullRequest.create! valid_attributes
      delete :destroy, {:id => pull_request.to_param}, valid_session
      response.should redirect_to(pull_requests_url)
    end
  end

end
